// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnTXQHMSYvA-9YtUZBHXGTed7K2TzgS0',
    appId: '1:636724350605:web:4edbbc7ce76a4ef57a5cc4',
    messagingSenderId: '636724350605',
    projectId: 'rideshare-2993f',
    authDomain: 'rideshare-2993f.firebaseapp.com',
    storageBucket: 'rideshare-2993f.appspot.com',
    measurementId: 'G-501H29FN8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAiF2PwvpV2rsr3PZEyM8EuSyNKFqSV0M',
    appId: '1:636724350605:android:6d2f7e8a74c0166a7a5cc4',
    messagingSenderId: '636724350605',
    projectId: 'rideshare-2993f',
    storageBucket: 'rideshare-2993f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNb4NZ9vYuV_S9jtI0tQD8ZxBuoxx38JU',
    appId: '1:636724350605:ios:aea4412d677540e77a5cc4',
    messagingSenderId: '636724350605',
    projectId: 'rideshare-2993f',
    storageBucket: 'rideshare-2993f.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNb4NZ9vYuV_S9jtI0tQD8ZxBuoxx38JU',
    appId: '1:636724350605:ios:aea4412d677540e77a5cc4',
    messagingSenderId: '636724350605',
    projectId: 'rideshare-2993f',
    storageBucket: 'rideshare-2993f.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
